### PR TITLE
Add GL_EXT_texture_offset_non_const

### PR DESCRIPTION
**Pull request by rg3igalia**

### CODE REVIEW

**Review by zmike — APPROVED** [review]
Approved by WG 23 Oct 2024. @gnl21 please assign + set milestone once you approve.

**Review by gnl21 — APPROVED** [review]

**Comment by gnl21** [comment]
Does this need assigning, @zmike? I was planning on just merging it.

**Comment by zmike** [comment]
Oh, right. Yeah go for it, not trying to tell you how to do your job :+1:

**Comment by pmistryNV** [comment]
@rg3igalia the spec should have clarifications on how it interacts with GL_ARB_sparse_texture2. Do you want me to file a bug?

**Comment by rg3igalia** [comment]
I guess so. I don't know what's the usual process here. Thanks!

**Pull request merged**
