### PR TITLE
Publish GLSL_arm_shader_core_builtins

### PR DESCRIPTION
**Pull request by kpet**
Change-Id: I33988b29010e274d0e5d906a17f3fed60b952486
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by kpet** [comment]
@gnl21 Is this missing anything to go in? Thanks!

**Comment by gnl21** [comment]
No, it's not missing anything. Sorry that it got missed.

**Comment by kpet** [comment]
Great, thanks! I guess I have the same question for https://github.com/KhronosGroup/GLSL/pull/195 then :)

**Comment by gnl21** [comment]
I thought that one had been stopped in favour of exposing the functionality in other ways. If it's still active then I'll look at it now.

**Comment by kpet** [comment]
The priority was SPIR-V but there are a few folks interested in GLSL support still. Thanks!

**Pull request merged**
